name: pd-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - pandas=1.2.4
  - bokeh
  - pylint
  - pytest
  - pip
  - pip:
    - fair
    - numpy-financial
    - openpyxl
